# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EachCategoryPageFinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(990, 841)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 780, 671, 16))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ProfileButton = QtWidgets.QPushButton(Dialog)
        self.ProfileButton.setGeometry(QtCore.QRect(60, 90, 121, 70))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(12)
        self.ProfileButton.setFont(font)
        self.ProfileButton.setObjectName("ProfileButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 810, 791, 16))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 280, 971, 480))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 969, 478))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.TitleLable = QtWidgets.QLabel(Dialog)
        self.TitleLable.setGeometry(QtCore.QRect(20, 180, 315, 70))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLable.setFont(font)
        self.TitleLable.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLable.setObjectName("TitleLable")
        self.SearchBox = QtWidgets.QTextEdit(Dialog)
        self.SearchBox.setGeometry(QtCore.QRect(510, 220, 391, 41))
        self.SearchBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.SearchBox.setTabChangesFocus(False)
        self.SearchBox.setObjectName("SearchBox")
        self.BackButton = QtWidgets.QPushButton(Dialog)
        self.BackButton.setGeometry(QtCore.QRect(850, 70, 111, 70))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(12)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.HomeButton = QtWidgets.QPushButton(Dialog)
        self.HomeButton.setGeometry(QtCore.QRect(60, 20, 121, 70))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(12)
        self.HomeButton.setFont(font)
        self.HomeButton.setObjectName("HomeButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(350, 40, 341, 131))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SearchButton = QtWidgets.QPushButton(Dialog)
        self.SearchButton.setGeometry(QtCore.QRect(900, 220, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(12)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Contact us via : @comfortablynumb7 on Telegram or 09908611517"))
        self.ProfileButton.setText(_translate("Dialog", "Profile"))
        self.label_3.setText(_translate("Dialog", "Company Address : Iran - Tehran - Narmak - IUST"))
        self.TitleLable.setText(_translate("Dialog", "Title"))
        self.SearchBox.setPlaceholderText(_translate("Dialog", "Search Here"))
        self.BackButton.setText(_translate("Dialog", "Back"))
        self.HomeButton.setText(_translate("Dialog", "Home"))
        self.label.setText(_translate("Dialog", "Runnn!"))
        self.SearchButton.setText(_translate("Dialog", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
