# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
lst = []
lst.append("Versions/Interface/clothes.png")
lst.append("Versions/Interface/delivery.png")
lst.append("Versions/Interface/phone.png")
lst.append("Versions/Interface/kitchen.png")
i = 0




class Ui_MainWindow(object):
    global lst
    global i

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo1 = QtWidgets.QLabel(self.centralwidget)
        self.photo1.setGeometry(QtCore.QRect(140, 130, 521, 311))
        self.photo1.setText("")
        self.photo1.setPixmap(QtGui.QPixmap("clothes.png"))
        self.photo1.setScaledContents(True)
        self.photo1.setObjectName("photo1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(390, 450, 131, 51))
        self.next.setObjectName("next")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setGeometry(QtCore.QRect(270, 450, 121, 51))
        self.previous.setObjectName("previous")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 490, 761, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 530, 751, 21))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCtegories = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.actionCtegories.setFont(font)
        self.actionCtegories.setObjectName("actionCtegories")
        self.actionProfile_Page = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.actionProfile_Page.setFont(font)
        self.actionProfile_Page.setObjectName("actionProfile_Page")
        self.actionLogin_Page = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.actionLogin_Page.setFont(font)
        self.actionLogin_Page.setObjectName("actionLogin_Page")
        self.actionFavorites = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.actionFavorites.setFont(font)
        self.actionFavorites.setObjectName("actionFavorites")
        self.menuMenu.addAction(self.actionCtegories)
        self.menuMenu.addAction(self.actionProfile_Page)
        self.menuMenu.addAction(self.actionLogin_Page)
        self.menuMenu.addAction(self.actionFavorites)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.next.clicked.connect(self.next_clicked)
        self.previous.clicked.connect(self.previous_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Home Page"))
        self.label_2.setText(_translate("MainWindow", "TOROB"))
        self.next.setText(_translate("MainWindow", "NEXT"))
        self.previous.setText(_translate("MainWindow", "PREVIOUS"))
        self.label_3.setText(_translate("MainWindow",
                                        "Contact us via : @comfortablynumb7 on Telegram or 09908611517                                                                                          "))
        self.label_4.setText(_translate("MainWindow", "Company Address : Iran - Tehran - Narmak - IUST "))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionCtegories.setText(_translate("MainWindow", "Ctegories"))
        self.actionProfile_Page.setText(_translate("MainWindow", "Profile Page"))
        self.actionLogin_Page.setText(_translate("MainWindow", "Login Page"))
        self.actionFavorites.setText(_translate("MainWindow", "Favorites"))


    def next_clicked(self):
        global i
        global lst
        i = i + 1
        if i > 3:
            i = 0
        self.photo1.setPixmap(QtGui.QPixmap(lst[i]))

    def previous_clicked(self):
        global i
        global lst
        i = i - 1
        if i < 0:
            i = 3
        self.photo1.setPixmap(QtGui.QPixmap(lst[i]))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
